### ISSUE TITLE
Hello. I using your mod and it will be good if u add russian localisation, please.

### ISSUE THREAD

**Issue by YanatoCherizhosa** [n1ghthavvk/stellaris-iniates#1]
l_russian:

 diminutive:0 "Уменьшенная"
 miniature:0 "Миниатюрная"
 minuscule:0 "Крошечная"
 microscopic:0 "Микро"
 nanoscopic:0 "Нано"
 infinitesimal:0 "Пико"

**Comment by n1ghthavvk** [comment]
Thank you for the translation. I'll add it for you!

**Comment by n1ghthavvk** [comment]
#eeffbd4f51ac935b31ea6a7b03931d46fc9443ed
